In [1]:
import requests
import pandas as pd

### Getting the data

In [2]:
response = requests.get('https://api.themoviedb.org/3/movie/popular?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=1').json()
response

{'page': 1,
 'total_results': 10000,
 'total_pages': 500,
 'results': [{'popularity': 818.916,
   'vote_count': 12063,
   'video': False,
   'poster_path': '/5vHssUeVe25bMrof1HyaPyWgaP.jpg',
   'id': 245891,
   'adult': False,
   'backdrop_path': '/lvjRFFyNLdaMWIMYQvoebeO1JlF.jpg',
   'original_language': 'en',
   'original_title': 'John Wick',
   'genre_ids': [28, 53],
   'title': 'John Wick',
   'vote_average': 7.2,
   'overview': 'Ex-hitman John Wick comes out of retirement to track down the gangsters that took everything from him.',
   'release_date': '2014-10-22'},
  {'popularity': 427.078,
   'vote_count': 2778,
   'video': False,
   'poster_path': '/xBHvZcjRiWyobQ9kxBhO6B2dtRI.jpg',
   'id': 419704,
   'adult': False,
   'backdrop_path': '/5BwqwxMEjeFtdknRV792Svo0K1v.jpg',
   'original_language': 'en',
   'original_title': 'Ad Astra',
   'genre_ids': [18, 878],
   'title': 'Ad Astra',
   'vote_average': 6,
   'overview': 'The near future, a time when both hope and hardships drive humanity to look to the stars and beyond. While a mysterious phenomenon menaces to destroy life on planet Earth, astronaut Roy McBride undertakes a mission across the immensity of space and its many perils to uncover the truth about a lost expedition that decades before boldly faced emptiness and silence in search of the unknown.',
   'release_date': '2019-09-17'},
  {'popularity': 372.268,
   'vote_count': 2062,
   'video': False,
   'poster_path': '/y95lQLnuNKdPAzw9F9Ab8kJ80c3.jpg',
   'id': 38700,
   'adult': False,
   'backdrop_path': '/upUy2QhMZEmtypPW3PdieKLAHxh.jpg',
   'original_language': 'en',
   'original_title': 'Bad Boys for Life',
   'genre_ids': [28, 80, 53],
   'title': 'Bad Boys for Life',
   'vote_average': 6.9,
   'overview': 'Marcus and Mike are forced to confront new threats, career changes, and midlife crises as they join the newly created elite team AMMO of the Miami police department to take down the ruthless Armando Armas, the vicious leader of a Miami drug cartel.',
   'release_date': '2020-01-15'},
  {'popularity': 366.904,
   'vote_count': 5043,
   'video': False,
   'poster_path': '/2bXbqYdUdNVa8VIWXVfclP2ICtT.jpg',
   'id': 420818,
   'adult': False,
   'backdrop_path': '/nRXO2SnOA75OsWhNhXstHB8ZmI3.jpg',
   'original_language': 'en',
   'original_title': 'The Lion King',
   'genre_ids': [12, 10751],
   'title': 'The Lion King',
   'vote_average': 7.1,
   'overview': "Simba idolizes his father, King Mufasa, and takes to heart his own royal destiny. But not everyone in the kingdom celebrates the new cub's arrival. Scar, Mufasa's brother—and former heir to the throne—has plans of his own. The battle for Pride Rock is ravaged with betrayal, tragedy and drama, ultimately resulting in Simba's exile. With help from a curious pair of newfound friends, Simba will have to figure out how to grow up and take back what is rightfully his.",
   'release_date': '2019-07-12'},
  {'popularity': 355.501,
   'vote_count': 7153,
   'video': False,
   'poster_path': '/c9XxwwhPHdaImA2f1WEfEsbhaFB.jpg',
   'id': 351286,
   'adult': False,
   'backdrop_path': '/3s9O5af2xWKWR5JzP2iJZpZeQQg.jpg',
   'original_language': 'en',
   'original_title': 'Jurassic World: Fallen Kingdom',
   'genre_ids': [28, 12, 878],
   'title': 'Jurassic World: Fallen Kingdom',
   'vote_average': 6.5,
   'overview': 'Three years after the demise of Jurassic World, a volcanic eruption threatens the remaining dinosaurs on the isla Nublar, so Claire Dearing, the former park manager, recruits Owen Grady to help prevent the extinction of the dinosaurs once again.',
   'release_date': '2018-06-06'},
  {'popularity': 336.364,
   'vote_count': 1153,
   'video': False,
   'poster_path': '/8WUVHemHFH2ZIP6NWkwlHWsyrEL.jpg',
   'id': 338762,
   'adult': False,
   'backdrop_path': '/ocUrMYbdjknu2TwzMHKT9PBBQRw.jpg',
   'original_language': 'en',
   'original_title': 'Bloodshot',
   'genre_ids': [28, 878],
   'title': 'Bloodshot',
   'vote_average': 7.3,
   'overview': "After he and his wife are murdered, marine Ray Garrison is resurrected by a team of scientists. Enhanced with nanotechnology, he becomes a superhuman, biotech killing machine—'Bloodshot'. As Ray first trains with fellow super-soldiers, he cannot recall anything from his former life. But when his memories flood back and he remembers the man that killed both him and his wife, he breaks out of the facility to get revenge, only to discover that there's more to the conspiracy than he thought.",
   'release_date': '2020-02-20'},
  {'popularity': 274.351,
   'vote_count': 410,
   'video': False,
   'poster_path': '/jjMJy5OxJHpFIaboCklDIYdcfpD.jpg',
   'id': 504562,
   'adult': False,
   'backdrop_path': '/mJoZVYRTtPI6aMPb1UanuXFC1Zw.jpg',
   'original_language': 'en',
   'original_title': 'Motherless Brooklyn',
   'genre_ids': [18, 9648, 53],
   'title': 'Motherless Brooklyn',
   'vote_average': 6.9,
   'overview': 'New York City, 1957. Lionel Essrog, a private detective living with Tourette syndrome, tries to solve the murder of his mentor and best friend, armed only with vague clues and the strength of his obsessive mind…',
   'release_date': '2019-10-31'},
  {'popularity': 239.659,
   'vote_count': 3720,
   'video': False,
   'poster_path': '/s5HQf2Gb3lIO2cRcFwNL9sn1o1o.jpg',
   'id': 335988,
   'adult': False,
   'backdrop_path': '/1n00NlOGRFZVs8coBxyZLm5l4EC.jpg',
   'original_language': 'en',
   'original_title': 'Transformers: The Last Knight',
   'genre_ids': [28, 12, 878, 53],
   'title': 'Transformers: The Last Knight',
   'vote_average': 6,
   'overview': 'Autobots and Decepticons are at war, with humans on the sidelines. Optimus Prime is gone. The key to saving our future lies buried in the secrets of the past, in the hidden history of Transformers on Earth.',
   'release_date': '2017-06-16'},
  {'popularity': 228.535,
   'vote_count': 2419,
   'video': False,
   'poster_path': '/h4VB6m0RwcicVEZvzftYZyKXs6K.jpg',
   'id': 495764,
   'adult': False,
   'backdrop_path': '/jiqD14fg7UTZOT6qgvzTmfRYpWI.jpg',
   'original_language': 'en',
   'original_title': 'Birds of Prey (and the Fantabulous Emancipation of One Harley Quinn)',
   'genre_ids': [28, 35, 80],
   'title': 'Birds of Prey (and the Fantabulous Emancipation of One Harley Quinn)',
   'vote_average': 7.1,
   'overview': 'Harley Quinn joins forces with a singer, an assassin and a police detective to help a young girl who had a hit placed on her after she stole a rare diamond from a crime lord.',
   'release_date': '2020-02-05'},
  {'popularity': 222.339,
   'vote_count': 456,
   'video': False,
   'poster_path': '/dvjFM3GgYm3gDZ6Ulw0JurDYs4r.jpg',
   'id': 13004,
   'adult': False,
   'backdrop_path': '/mtZh7DHYcwiE8lQ2XrcaMd78CId.jpg',
   'original_language': 'en',
   'original_title': 'Barbie and the Diamond Castle',
   'genre_ids': [16, 10751],
   'title': 'Barbie and the Diamond Castle',
   'vote_average': 7.1,
   'overview': "Liana and Alexa (Barbie and Teresa) are best friends who share everything, including their love of singing. One day while walking through the forest home from the village, the girls meet an old beggar who gives them a magical mirror. As they clean the mirror and sing, a musical apprentice muse named Melody appears in the mirror's surface, and tells the girls about the secret of the Diamond Castle.",
   'release_date': '2008-01-01'},
  {'popularity': 222.136,
   'vote_count': 1581,
   'video': False,
   'poster_path': '/8ZX18L5m6rH5viSYpRnTSbb9eXh.jpg',
   'id': 619264,
   'adult': False,
   'backdrop_path': '/3tkDMNfM2YuIAJlvGO6rfIzAnfG.jpg',
   'original_language': 'es',
   'original_title': 'El hoyo',
   'genre_ids': [18, 878],
   'title': 'The Platform',
   'vote_average': 7.2,
   'overview': 'A mysterious place, an indescribable prison, a deep hole. An unknown number of levels. Two inmates living on each level. A descending platform containing food for all of them. An inhuman fight for survival, but also an opportunity for solidarity…',
   'release_date': '2019-11-08'},
  {'popularity': 194.985,
   'vote_count': 434,
   'video': False,
   'poster_path': '/wzkcVyLQjA5x2zqzu9zzCd7Cwdg.jpg',
   'id': 443791,
   'adult': False,
   'backdrop_path': '/fYPiQewg7ogbzro2XcCTACSB2KC.jpg',
   'original_language': 'en',
   'original_title': 'Underwater',
   'genre_ids': [28, 27, 878, 53],
   'title': 'Underwater',
   'vote_average': 6.4,
   'overview': 'After an earthquake destroys their underwater station, six researchers must navigate two miles along the dangerous, unknown depths of the ocean floor to make it to safety in a race against time.',
   'release_date': '2020-01-08'},
  {'popularity': 191.652,
   'vote_count': 3704,
   'video': False,
   'poster_path': '/db32LaOibwEliAmSL2jjDF6oDdj.jpg',
   'id': 181812,
   'adult': False,
   'backdrop_path': '/jOzrELAzFxtMx2I4uDGHOotdfsS.jpg',
   'original_language': 'en',
   'original_title': 'Star Wars: The Rise of Skywalker',
   'genre_ids': [28, 12, 878],
   'title': 'Star Wars: The Rise of Skywalker',
   'vote_average': 6.5,
   'overview': 'The surviving Resistance faces the First Order once again as the journey of Rey, Finn and Poe Dameron continues. With the power and knowledge of generations behind them, the final battle begins.',
   'release_date': '2019-12-18'},
  {'popularity': 189.881,
   'vote_count': 1860,
   'video': False,
   'poster_path': '/aQvJ5WPzZgYVDrxLX4R6cLJCEaQ.jpg',
   'id': 454626,
   'adult': False,
   'backdrop_path': '/stmYfCUGd8Iy6kAMBr6AmWqx8Bq.jpg',
   'original_language': 'en',
   'original_title': 'Sonic the Hedgehog',
   'genre_ids': [28, 16, 35, 878, 10751],
   'title': 'Sonic the Hedgehog',
   'vote_average': 7.4,
   'overview': 'Based on the global blockbuster videogame franchise from Sega, Sonic the Hedgehog tells the story of the world’s speediest hedgehog as he embraces his new home on Earth. In this live-action adventure comedy, Sonic and his new best friend team up to defend the planet from the evil genius Dr. Robotnik and his plans for world domination.',
   'release_date': '2020-02-12'},
  {'popularity': 182.633,
   'vote_count': 3620,
   'video': False,
   'poster_path': '/cFQHMUmxaO3PEDo5lxuQC8MCRIH.jpg',
   'id': 159824,
   'adult': False,
   'backdrop_path': '/h3t4zZPteUPqyDBrmz5Z2zzGM61.jpg',
   'original_language': 'en',
   'original_title': 'Hotel Transylvania 2',
   'genre_ids': [16, 35, 14, 10751],
   'title': 'Hotel Transylvania 2',
   'vote_average': 6.7,
   'overview': 'When the old-old-old-fashioned vampire Vlad arrives at the hotel for an impromptu family get-together, Hotel Transylvania is in for a collision of supernatural old-school and modern day cool.',
   'release_date': '2015-09-21'},
  {'popularity': 167.871,
   'vote_count': 2811,
   'video': False,
   'poster_path': '/bB42KDdfWkOvmzmYkmK58ZlCa9P.jpg',
   'id': 512200,
   'adult': False,
   'backdrop_path': '/hreiLoPysWG79TsyQgMzFKaOTF5.jpg',
   'original_language': 'en',
   'original_title': 'Jumanji: The Next Level',
   'genre_ids': [12, 35, 14],
   'title': 'Jumanji: The Next Level',
   'vote_average': 6.8,
   'overview': 'As the gang return to Jumanji to rescue one of their own, they discover that nothing is as they expect. The players will have to brave parts unknown and unexplored in order to escape the world’s most dangerous game.',
   'release_date': '2019-12-04'},
  {'popularity': 162.811,
   'vote_count': 1080,
   'video': False,
   'poster_path': '/4U7hpTK0XTQBKT5X60bKmJd05ha.jpg',
   'id': 570670,
   'adult': False,
   'backdrop_path': '/uZMZyvarQuXLRqf3xdpdMqzdtjb.jpg',
   'original_language': 'en',
   'original_title': 'The Invisible Man',
   'genre_ids': [27, 878, 53],
   'title': 'The Invisible Man',
   'vote_average': 7.1,
   'overview': "When Cecilia's abusive ex takes his own life and leaves her his fortune, she suspects his death was a hoax. As a series of coincidences turn lethal, Cecilia works to prove that she is being hunted by someone nobody can see.",
   'release_date': '2020-02-26'},
  {'popularity': 148.821,
   'vote_count': 2966,
   'video': False,
   'poster_path': '/jEMF8s7k4XsTnldISqtD0IuGrnS.jpg',
   'id': 10865,
   'adult': False,
   'backdrop_path': '/fYr0fqT9NImOuaN1QgnDHgGh4Ci.jpg',
   'original_language': 'en',
   'original_title': 'Atlantis: The Lost Empire',
   'genre_ids': [12, 16, 878, 10751],
   'title': 'Atlantis: The Lost Empire',
   'vote_average': 6.9,
   'overview': "The world's most highly qualified crew of archaeologists and explorers is led by historian Milo Thatch as they board the incredible 1,000-foot submarine Ulysses and head deep into the mysteries of the sea. The underwater expedition takes an unexpected turn when the team's mission must switch from exploring Atlantis to protecting it.",
   'release_date': '2001-06-02'},
  {'popularity': 141.067,
   'vote_count': 2670,
   'video': False,
   'poster_path': '/nrsx0jEaBgXq4PWo7SooSnYJTv.jpg',
   'id': 274855,
   'adult': False,
   'backdrop_path': '/79X8JkGxzc1tJMi0KxUSaPLooVg.jpg',
   'original_language': 'en',
   'original_title': 'Geostorm',
   'genre_ids': [28, 878, 53],
   'title': 'Geostorm',
   'vote_average': 5.8,
   'overview': "After an unprecedented series of natural disasters threatened the planet, the world's leaders came together to create an intricate network of satellites to control the global climate and keep everyone safe. But now, something has gone wrong: the system built to protect Earth is attacking it, and it becomes a race against the clock to uncover the real threat before a worldwide geostorm wipes out everything and everyone along with it.",
   'release_date': '2017-10-13'},
  {'popularity': 140.272,
   'vote_count': 746,
   'video': False,
   'poster_path': '/f4aul3FyD3jv3v4bul1IrkWZvzq.jpg',
   'id': 508439,
   'adult': False,
   'backdrop_path': '/xFxk4vnirOtUxpOEWgA1MCRfy6J.jpg',
   'original_language': 'en',
   'original_title': 'Onward',
   'genre_ids': [12, 16, 35, 14, 10751],
   'title': 'Onward',
   'vote_average': 8,
   'overview': 'In a suburban fantasy world, two teenage elf brothers embark on an extraordinary quest to discover if there is still a little magic left out there.',
   'release_date': '2020-02-29'}]}

In [3]:
# Create empty lists for different columns
popularity = []
vote_count = []
orig_lang = []
title = []
vote_avg = []
overview = []
rel_date = []

d = {'name':['x','y'],'age':[10,20]}
df = pd.DataFrame(d)
df

  name  age
0    x   10
1    y   20

In [4]:
# Fetching data from 'results': 

for i in response['results']:
    popularity.append(i['popularity'])
    vote_count.append(i['vote_count'])
    orig_lang.append(i['original_language'])
    title.append(i['title'])
    vote_avg.append(i['vote_average'])
    overview.append(i['overview'])
    rel_date.append(i['release_date'])
    
d = {'title':title,'overview':overview,'original_lang':orig_lang,'rel_date':rel_date,'popularity':popularity,'vote_count':vote_count,'vote_average':vote_avg}
df = pd.DataFrame(d)
df

,title,overview,original_lang,rel_date,popularity,vote_count,vote_average
0,John Wick,Ex-hitman John Wick comes out of retirement to...,en,2014-10-22,818.916,12063,7.2
1,Ad Astra,"The near future, a time when both hope and har...",en,2019-09-17,427.078,2778,6.0
2,Bad Boys for Life,Marcus and Mike are forced to confront new thr...,en,2020-01-15,372.268,2062,6.9
3,The Lion King,"Simba idolizes his father, King Mufasa, and ta...",en,2019-07-12,366.904,5043,7.1
4,Jurassic World: Fallen Kingdom,Three years after the demise of Jurassic World...,en,2018-06-06,355.501,7153,6.5
5,Bloodshot,"After he and his wife are murdered, marine Ray...",en,2020-02-20,336.364,1153,7.3
6,Motherless Brooklyn,"New York City, 1957. Lionel Essrog, a private ...",en,2019-10-31,274.351,410,6.9
7,Transformers: The Last Knight,"Autobots and Decepticons are at war, with huma...",en,2017-06-16,239.659,3720,6.0
8,Birds of Prey (and the Fantabulous Emancipatio...,"Harley Quinn joins forces with a singer, an as...",en,2020-02-05,228.535,2419,7.1
9,Barbie and the Diamond Castle,Liana and Alexa (Barbie and Teresa) are best f...,en,2008-01-01,222.339,456,7.1
10,The Platform,"A mysterious place, an indescribable prison, a...",es,2019-11-08,222.136,1581,7.2
11,Underwater,After an earthquake destroys their underwater ...,en,2020-01-08,194.985,434,6.4
12,Star Wars: The Rise of Skywalker,The surviving Resistance faces the First Order...,en,2019-12-18,191.652,3704,6.5
13,Sonic the Hedgehog,Based on the global blockbuster videogame fran...,en,2020-02-12,189.881,1860,7.4
14,Hotel Transylvania 2,When the old-old-old-fashioned vampire Vlad ar...,en,2015-09-21,182.633,3620,6.7
15,Jumanji: The Next Level,As the gang return to Jumanji to rescue one of...,en,2019-12-04,167.871,2811,6.8
16,The Invisible Man,When Cecilia's abusive ex takes his own life a...,en,2020-02-26,162.811,1080,7.1
17,Atlantis: The Lost Empire,The world's most highly qualified crew of arch...,en,2001-06-02,148.821,2966,6.9
18,Geostorm,After an unprecedented series of natural disas...,en,2017-10-13,141.067,2670,5.8
19,Onward,"In a suburban fantasy world, two teenage elf b...",en,2020-02-29,140.272,746,8.0

In [5]:
final = pd.DataFrame()

In [6]:
for j in range(1,501):
    resp = requests.get('https://api.themoviedb.org/3/movie/popular?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={}'.format(j)).json()
    popularity = []
    vote_count = []
    orig_lang = []
    title = []
    vote_avg = []
    overview = []
    rel_date = []
    
    for i in resp['results']:
        popularity.append(i['popularity'])
        vote_count.append(i['vote_count'])
        orig_lang.append(i['original_language'])
        title.append(i['title'])
        vote_avg.append(i['vote_average'])
        overview.append(i['overview'])
        
        try:
            rel_date.append(i['release_date'])
        except:
            rel_date.append('NaN')
        
    d = {'title':title,'overview':overview,'original_lang':orig_lang,'rel_date':rel_date,'popularity':popularity,'vote_count':vote_count,'vote_average':vote_avg}
    df = pd.DataFrame(d)
    final = final.append(df,ignore_index=True)

In [7]:
final

,title,overview,original_lang,rel_date,popularity,vote_count,vote_average
0,John Wick,Ex-hitman John Wick comes out of retirement to...,en,2014-10-22,818.916,12063,7.2
1,Ad Astra,"The near future, a time when both hope and har...",en,2019-09-17,427.078,2778,6.0
2,Bad Boys for Life,Marcus and Mike are forced to confront new thr...,en,2020-01-15,372.268,2062,6.9
3,The Lion King,"Simba idolizes his father, King Mufasa, and ta...",en,2019-07-12,366.904,5043,7.1
4,Jurassic World: Fallen Kingdom,Three years after the demise of Jurassic World...,en,2018-06-06,355.501,7153,6.5
...,...,...,...,...,...,...,...
9995,The Punk Singer,"A look at the life of activist, musician, and ...",en,2013-11-29,8.864,46,7.3
9996,Ready to Rumble,Two slacker wrestling fans are devastated by t...,en,2000-04-07,8.864,93,5.1
9997,Coma,A young woman doctor discovers something sinis...,en,1978-01-06,8.863,181,6.7
9998,They Call Me Jeeg,Enzo Ceccotti comes into contact with a radioa...,it,2016-02-25,8.862,1714,7.5
9999,Z for Zachariah,"In the wake of a nuclear war, a young woman su...",en,2015-08-13,8.862,528,5.6

In [8]:
final.to_csv('movies_tmdb_popular.csv',index=False)

In [10]:
m = pd.read_csv('movies_tmdb_popular.csv')
m

,title,overview,original_lang,rel_date,popularity,vote_count,vote_average
0,John Wick,Ex-hitman John Wick comes out of retirement to...,en,2014-10-22,818.916,12063,7.2
1,Ad Astra,"The near future, a time when both hope and har...",en,2019-09-17,427.078,2778,6.0
2,Bad Boys for Life,Marcus and Mike are forced to confront new thr...,en,2020-01-15,372.268,2062,6.9
3,The Lion King,"Simba idolizes his father, King Mufasa, and ta...",en,2019-07-12,366.904,5043,7.1
4,Jurassic World: Fallen Kingdom,Three years after the demise of Jurassic World...,en,2018-06-06,355.501,7153,6.5
...,...,...,...,...,...,...,...
9995,The Punk Singer,"A look at the life of activist, musician, and ...",en,2013-11-29,8.864,46,7.3
9996,Ready to Rumble,Two slacker wrestling fans are devastated by t...,en,2000-04-07,8.864,93,5.1
9997,Coma,A young woman doctor discovers something sinis...,en,1978-01-06,8.863,181,6.7
9998,They Call Me Jeeg,Enzo Ceccotti comes into contact with a radioa...,it,2016-02-25,8.862,1714,7.5
9999,Z for Zachariah,"In the wake of a nuclear war, a young woman su...",en,2015-08-13,8.862,528,5.6